framework:
    workflows:
       vehicule:
           type: 'state_machine'
           marking_store:
               type: 'method'
               property: 'state'
           supports:
               - App\Entity\Vehicule
           initial_marking: en_commande
           places:
               - en_commande
               - en_stock
               - reserve
               - vendu
           transitions:
               mettre_en_stock:
                   from: en_commande
                   to: en_stock
               reserver:
                   from: en_stock
                   to: reserve
               vendre:
                   from:
                       - en_stock
                       - reserve
                   to: vendu 
